In [ ]:
import sys
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import seaborn as sns
print("Library versions")
print("-" * 40)
print(f"Pandas       :  {pd.__version__}")
print(f"Numpy        :  {np.__version__}")
print(f"Scikit-learn :  {sklearn.__version__}")
print(f"Matplotlib   :  {matplotlib.__version__}")
print(f"Seaborn      :  {sns.__version__}")

Library versions
----------------------------------------
Pandas       :  2.2.2
Numpy        :  2.0.2
Scikit-learn :  1.6.1
Matplotlib   :  3.10.0
Seaborn      :  0.13.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from pandas import read_excel
df=read_excel('placement_predict_50k Dataset.csv')
df.head(5)
df.tail(5)
df.shape
rows, columns=df.shape
df.dtypes

StudentID               int64
Gender                 object
City                   object
CollegeTier            object
Stream                 object
Specialisation         object
Hostel                 object
HistoryOfBacklogs      object
SGPA_Sem1             float64
SGPA_Sem2             float64
SGPA_Sem3             float64
SGPA_Sem4             float64
SGPA_Sem5             float64
SGPA_Sem6             float64
SGPA_Sem7             float64
SGPA_Sem8             float64
CGPA                  float64
AttendancePercent     float64
Internships             int64
Projects                int64
Workshops             float64
Certifications          int64
Publications            int64
AptitudeTestScore     float64
SoftSkillsRating      float64
CodingTestScore       float64
MockInterviewScore    float64
ExtraCurricular         int64
CGPA_Tier              object
PlacementStatus         int64
IsAnomaly               int64
Salary Package        float64
dtype: object

In [ ]:
missing_data=pd.DataFrame({
    "Missing Values":df.isnull().sum(),
    "Missing Values Percentage":(df.isnull().sum()/rows)*100
})
missing_data

                    Missing Values  Missing Values Percentage
StudentID                        0                      0.000
Gender                           0                      0.000
City                             0                      0.000
CollegeTier                      0                      0.000
Stream                           0                      0.000
Specialisation                   0                      0.000
Hostel                           0                      0.000
HistoryOfBacklogs                0                      0.000
SGPA_Sem1                        0                      0.000
SGPA_Sem2                        0                      0.000
SGPA_Sem3                        0                      0.000
SGPA_Sem4                        0                      0.000
SGPA_Sem5                        0                      0.000
SGPA_Sem6                        0                      0.000
SGPA_Sem7                        0                      0.000
SGPA_Sem8                        0                      0.000
CGPA                             0                      0.000
AttendancePercent                0                      0.000
Internships                      0                      0.000
Projects                         0                      0.000
Workshops                     4488                      8.976
Certifications                   0                      0.000
Publications                     0                      0.000
AptitudeTestScore             4029                      8.058
SoftSkillsRating              3526                      7.052
CodingTestScore               2976                      5.952
MockInterviewScore            4957                      9.914
ExtraCurricular                  0                      0.000
CGPA_Tier                        0                      0.000
PlacementStatus                  0                      0.000
IsAnomaly                        0                      0.000
Salary Package                   0                      0.000